### ISSUE TITLE
Discord invite is invalid

### ISSUE THREAD

**Issue by f0lio** [lapce/lapce.github.io#4]

**Comment by dzhou121** [comment]
Looks fine. What have you got?

**Comment by f0lio** [comment]
The [link](https://discord.com/invite/n8tGJ6Rn6D) leads me to a broken invite.

![Screenshot from 2022-03-23 16-52-35](https://user-images.githubusercontent.com/36214338/159741195-47839609-de77-4a0f-99f9-c2de804db5cc.png)

Potentially an IP ban ..?
